var	G_STATE_DISCONNECTED = 0,
	G_STATE_CONNECTING = 1,
	G_STATE_CONNECTED = 2,
	G_STATE_RUN = 3,
	G_STATE_LOADING = 4,

	M_STATE_NONE = 0,
	M_STATE_MAIN = 1,
	M_STATE_OPTIONS = 2,

	D_SCREEN_WIDTH = 640,
	D_SCREEN_HEIGHT = 480;
